#!/usr/bin/bash

# ======== Add the following to .config/i3blocks/config. ========
#[packages]
#label=
#interval=3600
# ======== End add ========

URGENT_VALUE=25
PACKAGE_COUNT=$(checkupdates | wc -l)

if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
#  echo "${PACKAGE_COUNT}" # full-text
  echo "${PACKAGE_COUNT}" # short-text
  echo ""
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
  fi
fi
